// 30+ Chinese tourist cities with full metadata
const cities = [
  { id:'beijing', name:'北京', province:'北京市', region:'华北', lat:39.9, lng:116.4, costLevel:4, foodScore:9, bestMonths:[4,5,9,10],
    attractions:['故宫','长城','颐和园','天坛','南锣鼓巷','798艺术区'], cuisines:['烤鸭','炸酱面','豆汁','卤煮','涮羊肉'],
    tags:['文化','历史','都市'], transportHubs:{trainStation:'北京南站',airport:'北京首都国际机场',busStation:'北京长途汽车站'}, avgHotelPrice:500 },
  { id:'shanghai', name:'上海', province:'上海市', region:'华东', lat:31.2, lng:121.5, costLevel:5, foodScore:8.5, bestMonths:[3,4,5,9,10,11],
    attractions:['外滩','迪士尼','豫园','南京路','东方明珠'], cuisines:['小笼包','生煎','红烧肉','本帮菜'],
    tags:['都市','美食','购物'], transportHubs:{trainStation:'上海虹桥站',airport:'上海浦东国际机场',busStation:'上海长途客运总站'}, avgHotelPrice:600 },
  { id:'hangzhou', name:'杭州', province:'浙江省', region:'华东', lat:30.3, lng:120.2, costLevel:3, foodScore:9, bestMonths:[3,4,5,9,10],
    attractions:['西湖','灵隐寺','雷峰塔','西溪湿地','宋城','九溪烟树'], cuisines:['龙井虾仁','东坡肉','西湖醋鱼','葱包桧'],
    tags:['山水','文化','美食','古镇'], transportHubs:{trainStation:'杭州东站',airport:'杭州萧山国际机场',busStation:'杭州汽车南站'}, avgHotelPrice:380 },
  { id:'chengdu', name:'成都', province:'四川省', region:'西南', lat:30.6, lng:104.1, costLevel:2, foodScore:10, bestMonths:[3,4,5,9,10,11],
    attractions:['宽窄巷子','大熊猫基地','锦里','都江堰','杜甫草堂','青城山'], cuisines:['火锅','串串香','麻婆豆腐','担担面','兔头'],
    tags:['美食','都市','文化'], transportHubs:{trainStation:'成都东站',airport:'成都天府国际机场',busStation:'成都汽车总站'}, avgHotelPrice:280 },
  { id:'xiamen', name:'厦门', province:'福建省', region:'华东', lat:24.5, lng:118.1, costLevel:3, foodScore:8, bestMonths:[3,4,5,10,11],
    attractions:['鼓浪屿','曾厝垵','南普陀寺','厦门大学','环岛路'], cuisines:['沙茶面','海蛎煎','姜母鸭','土笋冻'],
    tags:['海滨','美食','文艺'], transportHubs:{trainStation:'厦门北站',airport:'厦门高崎国际机场',busStation:'厦门长途汽车站'}, avgHotelPrice:350 },
  { id:'sanya', name:'三亚', province:'海南省', region:'华南', lat:18.3, lng:109.5, costLevel:4, foodScore:7, bestMonths:[10,11,12,1,2,3],
    attractions:['亚龙湾','天涯海角','蜈支洲岛','南山寺'], cuisines:['海鲜','椰子鸡','海南粉','清补凉'],
    tags:['海滨','度假'], transportHubs:{trainStation:'三亚站',airport:'三亚凤凰国际机场',busStation:'三亚汽车站'}, avgHotelPrice:550 },
  { id:'guilin', name:'桂林', province:'广西壮族自治区', region:'华南', lat:25.3, lng:110.3, costLevel:2, foodScore:7.5, bestMonths:[4,5,6,9,10],
    attractions:['漓江','阳朔','象鼻山','龙脊梯田','十里画廊'], cuisines:['桂林米粉','啤酒鱼','田螺酿'],
    tags:['山水','自然'], transportHubs:{trainStation:'桂林北站',airport:'桂林两江国际机场',busStation:'桂林汽车总站'}, avgHotelPrice:200 },
  { id:'lijiang', name:'丽江', province:'云南省', region:'西南', lat:26.9, lng:100.2, costLevel:3, foodScore:7.5, bestMonths:[4,5,9,10],
    attractions:['丽江古城','玉龙雪山','束河古镇','泸沽湖','虎跳峡'], cuisines:['腊排骨','鸡豆凉粉','纳西烤鱼','酥油茶'],
    tags:['古镇','山水','文艺'], transportHubs:{trainStation:'丽江站',airport:'丽江三义国际机场',busStation:'丽江客运站'}, avgHotelPrice:300 },
  { id:'dali', name:'大理', province:'云南省', region:'西南', lat:25.6, lng:100.3, costLevel:2, foodScore:7.5, bestMonths:[3,4,5,9,10,11],
    attractions:['洱海','大理古城','苍山','双廊','崇圣寺三塔'], cuisines:['大理酸辣鱼','凉鸡米线','烤乳扇'],
    tags:['山水','古镇','文艺'], transportHubs:{trainStation:'大理站',airport:'大理荒草坝机场',busStation:'大理客运站'}, avgHotelPrice:220 },
  { id:'kunming', name:'昆明', province:'云南省', region:'西南', lat:25.0, lng:102.7, costLevel:2, foodScore:8, bestMonths:[3,4,5,6,7,8,9,10],
    attractions:['石林','滇池','翠湖公园','西山'], cuisines:['过桥米线','汽锅鸡','宜良烤鸭','鲜花饼'],
    tags:['都市','自然','美食'], transportHubs:{trainStation:'昆明南站',airport:'昆明长水国际机场',busStation:'昆明南部客运站'}, avgHotelPrice:240 },
  { id:'lasa', name:'拉萨', province:'西藏自治区', region:'西南', lat:29.6, lng:91.1, costLevel:3, foodScore:6, bestMonths:[5,6,7,8,9],
    attractions:['布达拉宫','大昭寺','纳木错','八廓街','羊卓雍措'], cuisines:['藏面','甜茶','牦牛肉','糌粑'],
    tags:['文化','高原','朝圣'], transportHubs:{trainStation:'拉萨站',airport:'拉萨贡嘎机场',busStation:'拉萨客运站'}, avgHotelPrice:300 },
  { id:'xian', name:'西安', province:'陕西省', region:'西北', lat:34.3, lng:108.9, costLevel:2, foodScore:9, bestMonths:[3,4,5,9,10],
    attractions:['兵马俑','大雁塔','城墙','回民街','华清池'], cuisines:['肉夹馍','羊肉泡馍','凉皮','Biangbiang面'],
    tags:['历史','文化','美食'], transportHubs:{trainStation:'西安北站',airport:'西安咸阳国际机场',busStation:'西安城北客运站'}, avgHotelPrice:280 },
  { id:'chongqing', name:'重庆', province:'重庆市', region:'西南', lat:29.6, lng:106.5, costLevel:2, foodScore:9.5, bestMonths:[3,4,5,9,10,11],
    attractions:['洪崖洞','磁器口','长江索道','武隆天坑','解放碑'], cuisines:['重庆火锅','小面','酸辣粉','毛血旺'],
    tags:['美食','山水','都市'], transportHubs:{trainStation:'重庆北站',airport:'重庆江北国际机场',busStation:'重庆龙头寺汽车站'}, avgHotelPrice:250 },
  { id:'wuhan', name:'武汉', province:'湖北省', region:'华中', lat:30.6, lng:114.3, costLevel:2, foodScore:8.5, bestMonths:[3,4,5,9,10],
    attractions:['黄鹤楼','东湖','户部巷','武汉长江大桥'], cuisines:['热干面','豆皮','鸭脖','武昌鱼'],
    tags:['都市','美食','历史'], transportHubs:{trainStation:'武汉站',airport:'武汉天河国际机场',busStation:'武汉宏基客运站'}, avgHotelPrice:240 },
  { id:'changsha', name:'长沙', province:'湖南省', region:'华中', lat:28.2, lng:112.9, costLevel:2, foodScore:9, bestMonths:[3,4,5,9,10],
    attractions:['橘子洲','岳麓山','太平老街','湖南省博物馆'], cuisines:['臭豆腐','剁椒鱼头','口味虾','糖油粑粑'],
    tags:['美食','都市','文化'], transportHubs:{trainStation:'长沙南站',airport:'长沙黄花国际机场',busStation:'长沙汽车西站'}, avgHotelPrice:220 },
  { id:'nanjing', name:'南京', province:'江苏省', region:'华东', lat:32.1, lng:118.8, costLevel:3, foodScore:8, bestMonths:[3,4,5,9,10],
    attractions:['中山陵','夫子庙','明孝陵','总统府','玄武湖'], cuisines:['鸭血粉丝汤','盐水鸭','小笼包','牛肉锅贴'],
    tags:['历史','文化','都市'], transportHubs:{trainStation:'南京南站',airport:'南京禄口国际机场',busStation:'南京长途汽车站'}, avgHotelPrice:330 },
  { id:'suzhou', name:'苏州', province:'江苏省', region:'华东', lat:31.3, lng:120.6, costLevel:3, foodScore:8, bestMonths:[3,4,5,9,10],
    attractions:['拙政园','虎丘','寒山寺','周庄','平江路'], cuisines:['松鼠桂鱼','阳澄湖大闸蟹','苏式汤面','糖粥'],
    tags:['园林','古镇','文化'], transportHubs:{trainStation:'苏州北站',airport:'苏南硕放国际机场',busStation:'苏州汽车北站'}, avgHotelPrice:320 },
  { id:'qingdao', name:'青岛', province:'山东省', region:'华东', lat:36.1, lng:120.4, costLevel:3, foodScore:8, bestMonths:[5,6,7,8,9,10],
    attractions:['崂山','栈桥','八大关','啤酒博物馆','金沙滩'], cuisines:['青岛啤酒','辣炒蛤蜊','海鲜水饺','鲅鱼水饺'],
    tags:['海滨','美食','避暑'], transportHubs:{trainStation:'青岛北站',airport:'青岛胶东国际机场',busStation:'青岛长途汽车站'}, avgHotelPrice:320 },
  { id:'dalian', name:'大连', province:'辽宁省', region:'东北', lat:38.9, lng:121.6, costLevel:3, foodScore:7.5, bestMonths:[5,6,7,8,9],
    attractions:['星海广场','老虎滩','金石滩','旅顺口'], cuisines:['海鲜','铁板鱿鱼','焖子','海胆饺子'],
    tags:['海滨','避暑','都市'], transportHubs:{trainStation:'大连北站',airport:'大连周水子国际机场',busStation:'大连建设街汽车站'}, avgHotelPrice:300 },
  { id:'haerbin', name:'哈尔滨', province:'黑龙江省', region:'东北', lat:45.8, lng:126.5, costLevel:2, foodScore:7.5, bestMonths:[6,7,8,12,1],
    attractions:['冰雪大世界','中央大街','圣索菲亚教堂','太阳岛'], cuisines:['锅包肉','红肠','大列巴','马迭尔冰棍'],
    tags:['冰雪','城市','美食'], transportHubs:{trainStation:'哈尔滨西站',airport:'哈尔滨太平国际机场',busStation:'哈尔滨公路大桥站'}, avgHotelPrice:240 },
  { id:'guangzhou', name:'广州', province:'广东省', region:'华南', lat:23.1, lng:113.3, costLevel:4, foodScore:9.5, bestMonths:[10,11,12,1,2,3],
    attractions:['广州塔','白云山','陈家祠','沙面','长隆'], cuisines:['早茶','白切鸡','烧鹅','肠粉','煲仔饭'],
    tags:['美食','都市','购物'], transportHubs:{trainStation:'广州南站',airport:'广州白云国际机场',busStation:'广州省站'}, avgHotelPrice:420 },
  { id:'shenzhen', name:'深圳', province:'广东省', region:'华南', lat:22.5, lng:114.1, costLevel:5, foodScore:7.5, bestMonths:[10,11,12,1,2,3],
    attractions:['世界之窗','欢乐谷','深圳湾公园','东部华侨城'], cuisines:['肠粉','海鲜','潮汕菜','茶餐厅'],
    tags:['都市','购物','海滨'], transportHubs:{trainStation:'深圳北站',airport:'深圳宝安国际机场',busStation:'深圳罗湖汽车站'}, avgHotelPrice:450 },
  { id:'luoyang', name:'洛阳', province:'河南省', region:'华中', lat:34.6, lng:112.5, costLevel:2, foodScore:7.5, bestMonths:[4,5,9,10],
    attractions:['龙门石窟','白马寺','洛阳老城','关林'], cuisines:['洛阳水席','牛肉汤','不翻汤','牡丹花饼'],
    tags:['历史','文化'], transportHubs:{trainStation:'洛阳龙门站',airport:'洛阳北郊机场',busStation:'洛阳汽车站'}, avgHotelPrice:200 },
  { id:'huangshan', name:'黄山', province:'安徽省', region:'华东', lat:29.7, lng:118.3, costLevel:3, foodScore:7, bestMonths:[4,5,9,10,11],
    attractions:['黄山风景区','宏村','西递','屯溪老街'], cuisines:['臭鳜鱼','毛豆腐','徽州一品锅','黄山烧饼'],
    tags:['山水','古镇','自然'], transportHubs:{trainStation:'黄山北站',airport:'黄山屯溪国际机场',busStation:'黄山汽车站'}, avgHotelPrice:280 },
  { id:'zhangjiajie', name:'张家界', province:'湖南省', region:'华中', lat:29.1, lng:110.5, costLevel:2, foodScore:6.5, bestMonths:[4,5,6,9,10],
    attractions:['张家界国家森林公园','天门山','大峡谷','芙蓉镇'], cuisines:['三下锅','岩耳炖土鸡','土家腊肉'],
    tags:['山水','自然'], transportHubs:{trainStation:'张家界西站',airport:'张家界荷花国际机场',busStation:'张家界中心汽车站'}, avgHotelPrice:200 },
  { id:'tianjin', name:'天津', province:'天津市', region:'华北', lat:39.1, lng:117.2, costLevel:2, foodScore:8, bestMonths:[4,5,9,10],
    attractions:['天津之眼','五大道','意式风情区','古文化街'], cuisines:['狗不理包子','煎饼果子','耳朵眼炸糕','锅巴菜'],
    tags:['都市','美食','历史'], transportHubs:{trainStation:'天津西站',airport:'天津滨海国际机场',busStation:'天津通莎客运站'}, avgHotelPrice:260 },
  { id:'wuxi', name:'无锡', province:'江苏省', region:'华东', lat:31.6, lng:120.3, costLevel:3, foodScore:7.5, bestMonths:[3,4,5,9,10],
    attractions:['鼋头渚','灵山大佛','惠山古镇','拈花湾'], cuisines:['酱排骨','无锡小笼','太湖三白','桂花糖芋'],
    tags:['山水','古镇','园林'], transportHubs:{trainStation:'无锡东站',airport:'苏南硕放国际机场',busStation:'无锡汽车站'}, avgHotelPrice:300 },
  { id:'shenyang', name:'沈阳', province:'辽宁省', region:'东北', lat:41.8, lng:123.4, costLevel:2, foodScore:7, bestMonths:[5,6,7,8,9],
    attractions:['沈阳故宫','张氏帅府','北陵公园','棋盘山'], cuisines:['鸡架','老边饺子','熏肉大饼','锅包肉'],
    tags:['历史','都市'], transportHubs:{trainStation:'沈阳北站',airport:'沈阳桃仙国际机场',busStation:'沈阳客运站'}, avgHotelPrice:220 },
  { id:'zhenzhou', name:'郑州', province:'河南省', region:'华中', lat:34.8, lng:113.7, costLevel:2, foodScore:7, bestMonths:[3,4,5,9,10],
    attractions:['少林寺','河南博物院','嵩山','二七纪念塔'], cuisines:['胡辣汤','烩面','桶子鸡','灌汤包'],
    tags:['历史','文化'], transportHubs:{trainStation:'郑州东站',airport:'郑州新郑国际机场',busStation:'郑州长途汽车中心站'}, avgHotelPrice:200 },
  { id:'jinan', name:'济南', province:'山东省', region:'华东', lat:36.7, lng:117.0, costLevel:2, foodScore:7, bestMonths:[4,5,9,10],
    attractions:['趵突泉','大明湖','千佛山','芙蓉街'], cuisines:['把子肉','甜沫','油旋','九转大肠'],
    tags:['泉水','文化'], transportHubs:{trainStation:'济南西站',airport:'济南遥墙国际机场',busStation:'济南长途汽车总站'}, avgHotelPrice:240 },
  { id:'zhuhai', name:'珠海', province:'广东省', region:'华南', lat:22.3, lng:113.6, costLevel:3, foodScore:7, bestMonths:[10,11,12,1,2,3],
    attractions:['长隆海洋王国','情侣路','外伶仃岛','圆明新园'], cuisines:['海鲜','横琴蚝','斗门重壳蟹','茶果'],
    tags:['海滨','度假'], transportHubs:{trainStation:'珠海站',airport:'珠海金湾机场',busStation:'珠海拱北汽车站'}, avgHotelPrice:350 },
  { id:'haikou', name:'海口', province:'海南省', region:'华南', lat:20.0, lng:110.3, costLevel:2, foodScore:7, bestMonths:[10,11,12,1,2,3],
    attractions:['火山口','骑楼老街','假日海滩','万绿园'], cuisines:['清补凉','海南粉','老爸茶','抱罗粉'],
    tags:['海滨','都市'], transportHubs:{trainStation:'海口东站',airport:'海口美兰国际机场',busStation:'海口汽车总站'}, avgHotelPrice:240 },
  { id:'qinhuangdao', name:'秦皇岛', province:'河北省', region:'华北', lat:39.9, lng:119.6, costLevel:2, foodScore:7, bestMonths:[6,7,8,9],
    attractions:['北戴河','山海关','鸽子窝公园','老龙头'], cuisines:['海鲜','回记绿豆糕','四条包子'],
    tags:['海滨','避暑'], transportHubs:{trainStation:'秦皇岛站',airport:'秦皇岛北戴河机场',busStation:'秦皇岛长途汽车站'}, avgHotelPrice:200 },
  { id:'fuzhou', name:'福州', province:'福建省', region:'华东', lat:26.1, lng:119.3, costLevel:2, foodScore:8, bestMonths:[3,4,5,9,10,11], attractions:['三坊七巷','鼓山','西湖公园','平潭岛'], cuisines:['佛跳墙','鱼丸','肉燕','锅边糊','荔枝肉'], tags:['美食','文化','海滨'], transportHubs:{trainStation:'福州南站',airport:'福州长乐国际机场',busStation:'福州汽车北站'}, avgHotelPrice:260 },
  { id:'guiyang', name:'贵阳', province:'贵州省', region:'西南', lat:26.6, lng:106.7, costLevel:2, foodScore:8, bestMonths:[3,4,5,6,7,8,9,10], attractions:['黔灵山','青岩古镇','甲秀楼','天河潭','花溪公园'], cuisines:['酸汤鱼','肠旺面','丝娃娃','花溪牛肉粉','豆米火锅'], tags:['美食','山水','避暑'], transportHubs:{trainStation:'贵阳北站',airport:'贵阳龙洞堡国际机场',busStation:'贵阳金阳客站'}, avgHotelPrice:220 },
  { id:'nanning', name:'南宁', province:'广西壮族自治区', region:'华南', lat:22.8, lng:108.4, costLevel:2, foodScore:7.5, bestMonths:[3,4,5,9,10,11], attractions:['青秀山','南湖公园','广西民族博物馆','伊岭岩','大明山'], cuisines:['老友粉','柠檬鸭','酸嘢','卷筒粉','横县鱼生'], tags:['都市','美食','自然'], transportHubs:{trainStation:'南宁东站',airport:'南宁吴圩国际机场',busStation:'南宁琅东客运站'}, avgHotelPrice:200 },
  { id:'nanchang', name:'南昌', province:'江西省', region:'华东', lat:28.7, lng:115.9, costLevel:2, foodScore:7, bestMonths:[3,4,5,9,10], attractions:['滕王阁','八一广场','绳金塔','梅岭','南昌之星'], cuisines:['南昌拌粉','瓦罐汤','藜蒿炒腊肉','鄱阳湖银鱼'], tags:['历史','都市'], transportHubs:{trainStation:'南昌西站',airport:'南昌昌北国际机场',busStation:'南昌徐坊客运站'}, avgHotelPrice:200 },
  { id:'hefei', name:'合肥', province:'安徽省', region:'华东', lat:31.8, lng:117.3, costLevel:2, foodScore:7, bestMonths:[3,4,5,9,10], attractions:['包公园','逍遥津','三河古镇','安徽省博物馆','天鹅湖'], cuisines:['臭鳜鱼','包公鱼','庐州烤鸭','合肥小龙虾'], tags:['都市','历史'], transportHubs:{trainStation:'合肥南站',airport:'合肥新桥国际机场',busStation:'合肥客运总站'}, avgHotelPrice:210 },
  { id:'taiyuan', name:'太原', province:'山西省', region:'华北', lat:37.9, lng:112.6, costLevel:2, foodScore:7, bestMonths:[4,5,6,7,8,9], attractions:['晋祠','山西博物院','双塔寺','蒙山大佛','汾河公园'], cuisines:['刀削面','过油肉','太原头脑','莜面栲栳栳'], tags:['历史','文化'], transportHubs:{trainStation:'太原南站',airport:'太原武宿国际机场',busStation:'太原建南汽车站'}, avgHotelPrice:200 },
  { id:'shijiazhuang', name:'石家庄', province:'河北省', region:'华北', lat:38.0, lng:114.5, costLevel:2, foodScore:6.5, bestMonths:[4,5,6,7,8,9], attractions:['正定古城','隆兴寺','苍岩山','西柏坡','赵州桥'], cuisines:['驴肉火烧','缸炉烧饼','金毛狮子鱼','正定崩肝'], tags:['历史','都市'], transportHubs:{trainStation:'石家庄站',airport:'石家庄正定国际机场',busStation:'石家庄客运总站'}, avgHotelPrice:180 },
  { id:'changchun', name:'长春', province:'吉林省', region:'东北', lat:43.8, lng:125.3, costLevel:2, foodScore:7, bestMonths:[5,6,7,8,9], attractions:['伪满皇宫','净月潭','长影世纪城','南湖公园','长春世界雕塑园'], cuisines:['酱骨头','朝鲜冷面','长春炒粉','酸菜白肉'], tags:['都市','历史','冰雪'], transportHubs:{trainStation:'长春西站',airport:'长春龙嘉国际机场',busStation:'长春凯旋公路客运站'}, avgHotelPrice:200 },
  { id:'lanzhou', name:'兰州', province:'甘肃省', region:'西北', lat:36.1, lng:103.8, costLevel:2, foodScore:7.5, bestMonths:[5,6,7,8,9], attractions:['黄河铁桥','白塔山','甘肃省博物馆','五泉山','水墨丹霞'], cuisines:['兰州牛肉面','手抓羊肉','酿皮','灰豆子','黄焖羊肉'], tags:['美食','历史','黄河'], transportHubs:{trainStation:'兰州西站',airport:'兰州中川国际机场',busStation:'兰州客运中心'}, avgHotelPrice:210 },
  { id:'xining', name:'西宁', province:'青海省', region:'西北', lat:36.6, lng:101.8, costLevel:2, foodScore:6.5, bestMonths:[5,6,7,8,9], attractions:['塔尔寺','青海省博物馆','东关清真大寺','北禅寺','南山公园'], cuisines:['手抓羊肉','酿皮','尕面片','青海酸奶','羊肠面'], tags:['文化','高原'], transportHubs:{trainStation:'西宁站',airport:'西宁曹家堡机场',busStation:'西宁客运站'}, avgHotelPrice:190 },
  { id:'yinchuan', name:'银川', province:'宁夏回族自治区', region:'西北', lat:38.5, lng:106.3, costLevel:2, foodScore:7, bestMonths:[5,6,7,8,9], attractions:['西夏王陵','沙湖','镇北堡影视城','贺兰山岩画','水洞沟'], cuisines:['手抓羊肉','羊杂碎','烩肉','八宝茶'], tags:['历史','自然','文化'], transportHubs:{trainStation:'银川站',airport:'银川河东国际机场',busStation:'银川旅游汽车站'}, avgHotelPrice:200 },
  { id:'wulumuqi', name:'乌鲁木齐', province:'新疆维吾尔自治区', region:'西北', lat:43.8, lng:87.6, costLevel:2, foodScore:7.5, bestMonths:[5,6,7,8,9,10], attractions:['天山天池','国际大巴扎','红山公园','南山牧场','新疆博物馆'], cuisines:['大盘鸡','抓饭','烤包子','拉条子','馕包肉'], tags:['美食','自然','风情'], transportHubs:{trainStation:'乌鲁木齐站',airport:'乌鲁木齐地窝堡国际机场',busStation:'乌鲁木齐客运站'}, avgHotelPrice:240 },
  { id:'huhehaote', name:'呼和浩特', province:'内蒙古自治区', region:'华北', lat:40.8, lng:111.8, costLevel:2, foodScore:7, bestMonths:[5,6,7,8,9], attractions:['大召寺','内蒙古博物院','昭君墓','希拉穆仁草原','哈素海'], cuisines:['手把肉','烤羊腿','奶皮子','焙子','蒙古奶茶'], tags:['草原','文化','美食'], transportHubs:{trainStation:'呼和浩特东站',airport:'呼和浩特白塔国际机场',busStation:'呼和浩特长途汽车站'}, avgHotelPrice:200 },
  { id:'ningbo', name:'宁波', province:'浙江省', region:'华东', lat:29.9, lng:121.6, costLevel:3, foodScore:8, bestMonths:[3,4,5,9,10,11], attractions:['天一阁','老外滩','东钱湖','象山影视城','雪窦山'], cuisines:['宁波汤圆','红膏炝蟹','溪口千层饼','海鲜'], tags:['美食','海滨','文化'], transportHubs:{trainStation:'宁波站',airport:'宁波栎社国际机场',busStation:'宁波汽车南站'}, avgHotelPrice:300 },
  { id:'wenzhou', name:'温州', province:'浙江省', region:'华东', lat:28.0, lng:120.7, costLevel:3, foodScore:7.5, bestMonths:[3,4,5,9,10], attractions:['雁荡山','楠溪江','江心屿','洞头岛','南麂岛'], cuisines:['温州鱼丸','灯盏糕','糯米饭','猪脏粉'], tags:['海滨','山水','美食'], transportHubs:{trainStation:'温州南站',airport:'温州龙湾国际机场',busStation:'温州新城站'}, avgHotelPrice:280 },
  { id:'shaoxing', name:'绍兴', province:'浙江省', region:'华东', lat:30.0, lng:120.6, costLevel:2, foodScore:7.5, bestMonths:[3,4,5,9,10], attractions:['鲁迅故里','沈园','兰亭','东湖','柯岩'], cuisines:['绍兴黄酒','梅干菜扣肉','绍兴臭豆腐','茴香豆'], tags:['文化','古镇','美食'], transportHubs:{trainStation:'绍兴北站',airport:'杭州萧山国际机场',busStation:'绍兴客运中心'}, avgHotelPrice:240 },
  { id:'yangzhou', name:'扬州', province:'江苏省', region:'华东', lat:32.4, lng:119.4, costLevel:2, foodScore:8, bestMonths:[3,4,5,9,10], attractions:['瘦西湖','个园','大明寺','何园','东关街'], cuisines:['扬州炒饭','蟹粉狮子头','大煮干丝','三丁包子'], tags:['园林','美食','文化'], transportHubs:{trainStation:'扬州东站',airport:'扬泰机场',busStation:'扬州汽车西站'}, avgHotelPrice:250 },
  { id:'yantai', name:'烟台', province:'山东省', region:'华东', lat:37.5, lng:121.4, costLevel:2, foodScore:7.5, bestMonths:[5,6,7,8,9], attractions:['蓬莱阁','长岛','烟台山','养马岛','金沙滩'], cuisines:['烟台焖子','蓬莱小面','福山大面','海鲜'], tags:['海滨','美食','避暑'], transportHubs:{trainStation:'烟台南站',airport:'烟台蓬莱国际机场',busStation:'烟台汽车总站'}, avgHotelPrice:260 },
  { id:'dunhuang', name:'敦煌', province:'甘肃省', region:'西北', lat:40.1, lng:94.7, costLevel:3, foodScore:6.5, bestMonths:[5,6,7,8,9,10], attractions:['莫高窟','鸣沙山','月牙泉','玉门关','雅丹地貌'], cuisines:['驴肉黄面','敦煌酿皮','羊肉粉汤','杏皮水'], tags:['历史','文化','沙漠'], transportHubs:{trainStation:'敦煌站',airport:'敦煌莫高国际机场',busStation:'敦煌汽车站'}, avgHotelPrice:280 },
  { id:'jiuzhaigou', name:'九寨沟', province:'四川省', region:'西南', lat:33.3, lng:104.0, costLevel:4, foodScore:6, bestMonths:[5,6,7,8,9,10], attractions:['九寨沟风景区','黄龙','神仙池','甲蕃古城','岷江源'], cuisines:['藏式火锅','青稞酒','酥油茶','牦牛肉'], tags:['山水','自然','高原'], transportHubs:{trainStation:'镇江关站',airport:'九寨黄龙机场',busStation:'九寨沟客运站'}, avgHotelPrice:380 },
  { id:'beihai', name:'北海', province:'广西壮族自治区', region:'华南', lat:21.5, lng:109.1, costLevel:2, foodScore:7.5, bestMonths:[3,4,5,10,11], attractions:['涠洲岛','银滩','北海老街','海底世界','冠头岭'], cuisines:['海鲜','虾饼','牛腩粉','沙虫','越南卷粉'], tags:['海滨','度假','美食'], transportHubs:{trainStation:'北海站',airport:'北海福成机场',busStation:'北海和信客运站'}, avgHotelPrice:190 },
  { id:'fenghuang', name:'凤凰古城', province:'湖南省', region:'华中', lat:28.0, lng:109.6, costLevel:2, foodScore:7, bestMonths:[3,4,5,9,10], attractions:['沱江','吊脚楼','虹桥','沈从文故居','南华山'], cuisines:['血粑鸭','酸鱼','姜糖','苗家米粉'], tags:['古镇','文化','山水'], transportHubs:{trainStation:'凤凰古城站',airport:'铜仁凤凰机场',busStation:'凤凰客运总站'}, avgHotelPrice:180 },
  { id:'kaifeng', name:'开封', province:'河南省', region:'华中', lat:34.8, lng:114.3, costLevel:2, foodScore:7.5, bestMonths:[3,4,5,9,10], attractions:['清明上河园','龙亭','大相国寺','开封府','铁塔'], cuisines:['灌汤包','炒凉粉','鲤鱼焙面','花生糕'], tags:['历史','文化','美食'], transportHubs:{trainStation:'开封北站',airport:'郑州新郑国际机场',busStation:'开封长途汽车站'}, avgHotelPrice:180 },
  { id:'xishuangbanna', name:'西双版纳', province:'云南省', region:'西南', lat:22.0, lng:100.8, costLevel:3, foodScore:8, bestMonths:[10,11,12,1,2,3], attractions:['热带植物园','野象谷','傣族园','告庄西双景','望天树'], cuisines:['傣味烧烤','竹筒饭','菠萝紫米饭','香茅草烤鱼'], tags:['热带','风情','美食','自然'], transportHubs:{trainStation:'西双版纳站',airport:'西双版纳嘎洒国际机场',busStation:'景洪客运站'}, avgHotelPrice:300 },
  { id:'xianggelila', name:'香格里拉', province:'云南省', region:'西南', lat:27.8, lng:99.7, costLevel:3, foodScore:6.5, bestMonths:[5,6,7,8,9], attractions:['松赞林寺','普达措','独克宗古城','梅里雪山','虎跳峡'], cuisines:['牦牛肉火锅','糌粑','酥油茶','藏式酸奶'], tags:['高原','自然','文化'], transportHubs:{trainStation:'香格里拉站',airport:'迪庆香格里拉机场',busStation:'香格里拉客运站'}, avgHotelPrice:280 },
  { id:'weihai', name:'威海', province:'山东省', region:'华东', lat:37.5, lng:122.1, costLevel:2, foodScore:7, bestMonths:[5,6,7,8,9], attractions:['刘公岛','成山头','海水浴场','天鹅湖','环海路'], cuisines:['海鲜','鲅鱼水饺','威海无花果','烧烤'], tags:['海滨','避暑','宜居'], transportHubs:{trainStation:'威海站',airport:'威海大水泊机场',busStation:'威海汽车站'}, avgHotelPrice:240 },
  { id:'datong', name:'大同', province:'山西省', region:'华北', lat:40.1, lng:113.3, costLevel:2, foodScore:6.5, bestMonths:[5,6,7,8,9], attractions:['云冈石窟','悬空寺','恒山','华严寺','大同古城墙'], cuisines:['刀削面','大同兔头','羊杂','黄糕'], tags:['历史','文化'], transportHubs:{trainStation:'大同南站',airport:'大同云冈机场',busStation:'大同汽车客运站'}, avgHotelPrice:190 },
  { id:'enshi', name:'恩施', province:'湖北省', region:'华中', lat:30.3, lng:109.5, costLevel:2, foodScore:7, bestMonths:[4,5,6,7,8,9,10], attractions:['恩施大峡谷','腾龙洞','土司城','屏山峡谷','女儿城'], cuisines:['合渣','土家油茶汤','恩施豆皮','榨广椒'], tags:['山水','自然','民族'], transportHubs:{trainStation:'恩施站',airport:'恩施许家坪机场',busStation:'恩施客运站'}, avgHotelPrice:200 },
  { id:'changbaishan', name:'长白山', province:'吉林省', region:'东北', lat:42.0, lng:128.1, costLevel:3, foodScore:6.5, bestMonths:[6,7,8,12,1,2], attractions:['天池','长白山瀑布','地下森林','聚龙泉','滑雪场'], cuisines:['铁锅炖','朝鲜族冷面','辣白菜','林蛙炖土豆'], tags:['山水','冰雪','自然'], transportHubs:{trainStation:'长白山站',airport:'长白山机场',busStation:'长白山池北客运站'}, avgHotelPrice:350 },
  { id:'mohe', name:'漠河', province:'黑龙江省', region:'东北', lat:53.0, lng:122.5, costLevel:3, foodScore:6, bestMonths:[6,7,8,12,1,2], attractions:['北极村','龙江第一湾','九曲十八弯','白桦林','圣诞村'], cuisines:['铁锅炖','杀猪菜','冻梨','林区山珍'], tags:['冰雪','极光','自然'], transportHubs:{trainStation:'漠河站',airport:'漠河古莲机场',busStation:'漠河客运站'}, avgHotelPrice:300 },
  { id:'yichang', name:'宜昌', province:'湖北省', region:'华中', lat:30.7, lng:111.3, costLevel:2, foodScore:7, bestMonths:[3,4,5,9,10], attractions:['三峡大坝','三峡人家','清江画廊','三游洞','西陵峡'], cuisines:['萝卜饺子','凉虾','红油小面','三峡苕酥'], tags:['山水','自然'], transportHubs:{trainStation:'宜昌东站',airport:'宜昌三峡机场',busStation:'宜昌长途汽车站'}, avgHotelPrice:200 },
  { id:'linzhi', name:'林芝', province:'西藏自治区', region:'西南', lat:29.7, lng:94.4, costLevel:3, foodScore:6, bestMonths:[3,4,5,9,10], attractions:['雅鲁藏布大峡谷','南迦巴瓦峰','巴松措','鲁朗林海','桃花沟'], cuisines:['石锅鸡','藏香猪','青稞饼','酥油茶'], tags:['自然','高原','花海'], transportHubs:{trainStation:'林芝站',airport:'林芝米林机场',busStation:'林芝客运站'}, avgHotelPrice:260 },
  { id:'foshan', name:'佛山', province:'广东省', region:'华南', lat:23.0, lng:113.1, costLevel:3, foodScore:8.5, bestMonths:[10,11,12,1,2,3], attractions:['祖庙','西樵山','清晖园','南风古灶','岭南天地'], cuisines:['双皮奶','顺德鱼生','盲公饼','大良炒鲜奶'], tags:['美食','文化','功夫之城'], transportHubs:{trainStation:'佛山西站',airport:'广州白云国际机场',busStation:'佛山粤运汽车站'}, avgHotelPrice:260 },
  { id:'xuzhou', name:'徐州', province:'江苏省', region:'华东', lat:34.3, lng:117.2, costLevel:2, foodScore:7, bestMonths:[4,5,9,10], attractions:['云龙湖','龟山汉墓','汉画像石馆','户部山','彭祖园'], cuisines:['地锅鸡','辣汤','饣它汤','徐州狗肉'], tags:['历史','美食'], transportHubs:{trainStation:'徐州东站',airport:'徐州观音国际机场',busStation:'徐州汽车总站'}, avgHotelPrice:200 },
  { id:'yueyang', name:'岳阳', province:'湖南省', region:'华中', lat:29.4, lng:113.1, costLevel:2, foodScore:7, bestMonths:[3,4,5,9,10], attractions:['岳阳楼','君山岛','洞庭湖','张谷英村'], cuisines:['岳阳三蒸','回头鱼','君山银针鸡片','洞庭银鱼'], tags:['历史','山水','美食'], transportHubs:{trainStation:'岳阳东站',airport:'长沙黄花国际机场',busStation:'岳阳洞庭汽车站'}, avgHotelPrice:180 },
  { id:'chengde', name:'承德', province:'河北省', region:'华北', lat:41.0, lng:117.9, costLevel:2, foodScore:6.5, bestMonths:[5,6,7,8,9], attractions:['避暑山庄','外八庙','普宁寺','双塔山','坝上草原'], cuisines:['平泉羊汤','御土荷叶鸡','碗坨','承德杏仁'], tags:['历史','避暑','自然'], transportHubs:{trainStation:'承德南站',airport:'承德普宁机场',busStation:'承德客运站'}, avgHotelPrice:200 },
  { id:'hongcun', name:'宏村', province:'安徽省', region:'华东', lat:30.0, lng:117.9, costLevel:2, foodScore:6.5, bestMonths:[3,4,5,9,10,11], attractions:['月沼','承志堂','南湖','塔川','卢村'], cuisines:['臭鳜鱼','毛豆腐','徽州一品锅','黄山烧饼'], tags:['古镇','文化','写生胜地'], transportHubs:{trainStation:'黄山北站',airport:'黄山屯溪国际机场',busStation:'宏村客运站'}, avgHotelPrice:220 },
  { id:'jingdezhen', name:'景德镇', province:'江西省', region:'华东', lat:29.3, lng:117.2, costLevel:2, foodScore:7, bestMonths:[3,4,5,9,10,11], attractions:['古窑民俗博览区','陶溪川','瑶里古镇','三宝村','浮梁古县衙'], cuisines:['碱水粑','冷粉','饺子粑','瓷泥煨鸡','景德镇板鸭'], tags:['文化','古镇','陶瓷'], transportHubs:{trainStation:'景德镇北站',airport:'景德镇罗家机场',busStation:'景德镇汽车站'}, avgHotelPrice:190 },
  { id:'jiujiang', name:'九江', province:'江西省', region:'华东', lat:29.7, lng:116.0, costLevel:2, foodScore:7, bestMonths:[3,4,5,9,10], attractions:['庐山','浔阳楼','白鹿洞书院','鄱阳湖','东林寺'], cuisines:['庐山石鸡','鄱阳湖胖鱼头','九江茶饼','修水哨子'], tags:['山水','历史','文化'], transportHubs:{trainStation:'九江站',airport:'九江庐山机场',busStation:'九江长途汽车站'}, avgHotelPrice:200 },
  { id:'wuyuan', name:'婺源', province:'江西省', region:'华东', lat:29.3, lng:117.9, costLevel:2, foodScore:7, bestMonths:[3,4,5,9,10,11], attractions:['篁岭','江湾','李坑','晓起','月亮湾'], cuisines:['糊豆腐','粉蒸肉','婺源汽糕','清明果','荷包红鲤鱼'], tags:['古镇','花海','山水','摄影'], transportHubs:{trainStation:'婺源站',airport:'景德镇罗家机场',busStation:'婺源客运站'}, avgHotelPrice:180 },
  { id:'jinggangshan', name:'井冈山', province:'江西省', region:'华东', lat:26.6, lng:114.2, costLevel:2, foodScore:6.5, bestMonths:[4,5,6,7,8,9,10], attractions:['井冈山风景区','黄洋界','五指峰','龙潭','茨坪'], cuisines:['井冈烟笋','石耳炖鸡','红军菜','炒血鸭'], tags:['山水','红色之旅','自然'], transportHubs:{trainStation:'井冈山站',airport:'井冈山机场',busStation:'井冈山客运站'}, avgHotelPrice:180 },
  { id:'ganzhou', name:'赣州', province:'江西省', region:'华东', lat:25.8, lng:115.0, costLevel:2, foodScore:7.5, bestMonths:[3,4,5,9,10,11], attractions:['赣州古城墙','通天岩','八境台','郁孤台','瑞金共和国摇篮'], cuisines:['赣南小炒鱼','宁都肉丸','信丰萝卜饺','烫皮'], tags:['历史','红色之旅','美食'], transportHubs:{trainStation:'赣州西站',airport:'赣州黄金机场',busStation:'赣州汽车站'}, avgHotelPrice:180 },
]

export default cities
